# -*- coding: utf-8 -*-
"""dfs_queen.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VygRIjmR4I3F_wOXWTLtXtmHJpMnX2Dq
"""

import time
import tracemalloc

def is_safe(board, row, col):

    for i in range(row):
        if board[i] == col:
            return False
        if abs(board[i] - col) == abs(i - row):
            return False
    return True

def dfs_nqueens(n, row=0, board=None):
    if board is None:
        board = []
    if row == n:
        return board[:]
    for col in range(n):
        if is_safe(board, row, col):
            board.append(col)
            result = dfs_nqueens(n, row + 1, board)
            if result:
                return result
            board.pop()
    return None

def solve_dfs(n):
    start = time.time()
    tracemalloc.start()

    result = dfs_nqueens(n)

    current, peak = tracemalloc.get_traced_memory()
    tracemalloc.stop()
    elapsed = time.time() - start

    return result, elapsed, peak / 1024  # memory in KB

# Test
for n in [10, 15, 30]:
    sol, t, mem = solve_dfs(n)
    print(f"N={n} | Time: {t:.4f}s | Memory: {mem:.2f}KB | Solved: {sol is not None}")