# -*- coding: utf-8 -*-
"""genetic algorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rhvm-Cw7JmRSzX1zsoKdbFmAFbBUNyid
"""

import random
import time
import tracemalloc

def fitness(board):
    n = len(board)
    conflicts = 0
    for i in range(n):
        for j in range(i + 1, n):
            if abs(board[i] - board[j]) == abs(i - j):
                conflicts += 1
    return conflicts

def mutate_heurstic(board, n):
    row = random.randint(0, n - 1)
    best_col = board[row]
    min_conf = n
    for col in range(n):
        conf = 0
        for i in range(n):
            if i != row:
                if board[i] == col or abs(board[i] - col) == abs(i - row):
                    conf += 1
        if conf < min_conf:
            min_conf = conf
            best_col = col
    board[row] = best_col
    return board

def genetic_algorithm(n, pop_size=20, max_gen=1000):
    population = [random.sample(range(n), n) for _ in range(pop_size)]

    for gen in range(max_gen):
        population.sort(key=lambda ind: fitness(ind))

        if fitness(population[0]) == 0:
            return population[0], True

        new_population = population[:2]

        while len(new_population) < pop_size:
            parent = random.choice(population[:pop_size // 2])
            child = parent[:]

            child = mutate_heurstic(child, n)
            new_population.append(child)

        population = new_population

    return population[0], fitness(population[0]) == 0

def solve_ga(n):
    start = time.time()
    tracemalloc.start()
    result, solved = genetic_algorithm(n)
    _, peak = tracemalloc.get_traced_memory()
    tracemalloc.stop()
    return result, time.time() - start, peak / 1024, solved

for n in [10, 30, 50, 100, 200, 500]:
    sol, t, mem, solved = solve_ga(n)
    print(f"N={n:3} | Time: {t:8.4f}s | Memory: {mem:8.2f}KB | Solved: {solved}")