# -*- coding: utf-8 -*-
"""simulating.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A-1V438Mvf3ZA1KXsblYaZqvPrqT2Qzb
"""

import random
import math
import time
import tracemalloc

def get_row_conflicts(board, n, row):
    conflicts = 0
    for i in range(n):
        if i == row: continue
        if abs(board[i] - board[row]) == abs(i - row):
            conflicts += 1
    return conflicts

def simulated_annealing(n):
    board = list(range(n))
    random.shuffle(board)

    current_conflicts = 0
    for i in range(n):
        for j in range(i + 1, n):
            if abs(board[i] - board[j]) == abs(i - j):
                current_conflicts += 1

    temperature = n * 1.0
    cooling_rate = 0.9999

    while current_conflicts > 0 and temperature > 0.001:
        r1, r2 = random.sample(range(n), 2)

        old_conflicts = get_row_conflicts(board, n, r1) + get_row_conflicts(board, n, r2)

        board[r1], board[r2] = board[r2], board[r1]

        new_conflicts_row = get_row_conflicts(board, n, r1) + get_row_conflicts(board, n, r2)

        delta = new_conflicts_row - old_conflicts

        if delta <= 0 or random.random() < math.exp(-delta / temperature):
            current_conflicts += delta
        else:
            board[r1], board[r2] = board[r2], board[r1]  # Undo swap

        temperature *= cooling_rate

    return board, current_conflicts == 0

def solve_sa(n):
    start = time.time()
    tracemalloc.start()
    result, solved = simulated_annealing(n)
    _, peak = tracemalloc.get_traced_memory()
    tracemalloc.stop()
    return time.time() - start, peak / 1024, solved

# running the tests
for n in [10, 30, 50, 100, 200, 500]:
    t, mem, solved = solve_sa(n)
    print(f"N={n:3} | Time: {t:8.4f}s | Memory: {mem:8.2f} KB | Solved: {solved}")